### ISSUE TITLE
Nasvet pri uvozu podatkov

### ISSUE THREAD

**Issue by anagolob3141** [anagolob3141/APPR-2017-18#1]
Pozdravljeni!

Imam dve vprašanji:
Pri uvozu podatkov bi želela zajeti po eno spletno stran za vsak datum v letu 2016, vendar moja koda deluje preveč počasi. Zanima me ali bi bilo ustrezno, če zajemem vsak mesec posebej in tabele shranim v CSV datoteko?
Poleg tega mi v prvem stolpcu tabele ne izpisuje datumov v lepi obliki in ne vem kako jih ustrezno popraviti.

**Comment by jaanos** [comment]
Če je koda počasna, bo čisto v redu, če podatke shraniš v CSV.

Sicer pa lahko celotno funkcijo `uvoziPodatke` napišeš tako, da funkcije `UstvariTabelo` sploh ne potrebuješ:
```R
uvoziPodatke <- function(datumi){
  lapply(datumi, function(datum) {
    paste0("http://www.xe.com/currencytables/?from=USD&date=", datum) %>% html_session() %>%
      read_html() %>% html_nodes(xpath="//table[@id='historicalRateTbl']") %>% .[[1]] %>%
      html_table() %>% mutate(datum = datum)
  }) %>% bind_rows()
}
```
Namesto dodajanja z zanko `for` (ki zna biti neučinkovito) si torej pripraviš seznam uvoženih razpredelnic, ki jih na koncu združiš s funkcijo `bind_rows`. Namesto zastarele funkcije `html` (zaradi katere je prihajalo do opozoril) raje uporabi `html_session` za povezovanje in `read_html` za branje podatkov v obliki HTML. Tabelo lahko potem prebereš kar s funkcijo `html_table` - ta poskrbi tudi za ustrezne tipe številskih stolpcev. Datum potem dodaš kot nov stolpec z `mutate` - funkcija `cbind` očitno ne ohranja lastnosti vektorjev in zato so bili datumi pretvorjeni v števila.

Sedaj imaš v razpredelnici dva številska stolpca na isti lestvici, tako da bo potrebno razpredelnico spraviti v obliko *tidy data*. Ime valute je odvisno od kratice, tako da lahko to daš v posebno tabelo. Preostanek lahko pretvoriš s funkcijo `melt` iz knjižnice `reshape2`:
```R
names(tabela1) <- c("kratica", "ime", "nakupni", "prodajni", "datum")
imena.valut <- tabela1[, 1:2] %>% unique()
tecaji <- melt(tabela1[, -2], measure.vars = c("nakupni", "prodajni"),
               variable.name = "tip", value.name = "tecaj")
```
Tukaj parametra `variable.name` in `value.name` določata imena stolpcev, ki ustrezajo imenom pretvorjenih stolpcev ter vrednostim v njih.

**Comment by anagolob3141** [comment]
Sem popravila. Najlepša hvala za odgovor.

**Comment by jaanos** [comment]
Ko odpraviš težavo v issueju, ga lahko zapreš s klikom na **Close issue** (ali **Close and comment**, če ob tem še kaj napišeš). Issueje lahko zapiraš tudi iz commitov - če v sporočilo ob commitu napišeš *Close #1* (kjer #1 nadomestiš z ustrezno številko issueja), se bo ustrezni issue zaprl, ko bo commit objavljen na GitHubu,
