### ISSUE TITLE
Uvoz in poročilo

### ISSUE THREAD

**Issue by jaanos** [anagolob3141/APPR-2017-18#2]
Prosim poskrbi za svoje poročilo (`projekt.Rmd`), da boš lahko v četrtek predstavila svoj projekt. Vanj torej vnesi opis podatkov (lahko vzameš iz `README.md`) ter nariši nekaj zanimivih grafov oziroma zemljevidov. Del, ki je ostal iz vzorca, pobriši, da se ti bo poročilo prevedlo. Svetujem, da iz glave odstraniš vrstico `runtime: shiny` - po shranjevanju se bo pojavil gumb *Knit*, s katerim lahko poročilo prevedeš v obliko HTML.

Uvoz ti trenutno ne deluje - ustavi se ti po uvozu razpredelnice `tabela.za.kratice`, saj v se naslednjih dveh vrsticah namesto nanjo sklicuješ na neobstoječo spremenljivko `tabela`.

Imena datotek vedno navajaj relativno glede na vrhnjo mapo projekta (npr. `podatki/tecaji1tretjina.csv`) - ta je namreč privzeto delovna mapa pri delu s projektom v RStudiu. Če nimaš odprtega projekta  - zgoraj desno piše *Project: (None)* - potem klikni tja in izberi *Open Project...* ter odpri datoteko `APPR-2017-18.Rproj` v mapi s tvojim projektom. Za tem delovnega imenika ne spreminjaj.

**Comment by anagolob3141** [comment]
Pozdravljeni,

prosim, če lahko posodobite moje spremembe. Sedaj bi sse poročilo moralo prevesti.

Hvala in lp,
Ana

**Comment by jaanos** [comment]
Prosim, če za ločila imenikov uporabljaš `/` in ne `\` - slednje bo delovalo le na Windowsih. Poleg tega namesto `read.csv` (s piko) uporabljaj funkcijo `read_csv` iz knjižnice `readr` - tako se bodo datumi prepoznali kot taki in bo zato izpis na grafu lepši (namesto prekrivajočega izpisa vseh datum se naredi lestvica z označenimi nekaj časovnimi točkami).

Poleg tega pride do napake pri računanju povprečij in odklonov valut - števila se namreč pretvorijo v nize. Namesto, da te podatke računaš v zanki `for`, spravi razpredelnico `tecaji.po.valutah` v obliki *tidy data* in želene podatke izračunaj iz nje:
```R
tecaji.po.valutah.tidy <- melt(tecaji.po.valutah, id.vars = "datumi",
                               variable.name = "valuta", value.name = "vrednost")
urejeni.odkloni <- tecaji.po.valutah.tidy %>%
  filter(valuta %in% c("EUR", "GBP", "CHF", "CAD", "AUD", "ZAR", "JPY")) %>%
  group_by(valuta) %>% summarise(povprecje = mean(vrednost), odklon = sd(vrednost)) %>%
  arrange(odklon)
```
Ker je odklon pri japonskih jenih veliko večji kot pri ostalih valutah, bi ga sicer bilo smiselno izločiti iz zadnjega grafa.

**Comment by anagolob3141** [comment]
Hvala, sem popravila.

**Comment by jaanos** [comment]
`\` se še vedno uporablja na naslednjih mestih:

https://github.com/anagolob3141/APPR-2017-18/blob/ef73fe7dfae9822e800ad7ce1a6e2dd59f6c0861/uvoz/uvoz.r#L36

https://github.com/anagolob3141/APPR-2017-18/blob/ef73fe7dfae9822e800ad7ce1a6e2dd59f6c0861/uvoz/uvoz.r#L45

https://github.com/anagolob3141/APPR-2017-18/blob/ef73fe7dfae9822e800ad7ce1a6e2dd59f6c0861/projekt.Rmd#L34
