### ISSUE TITLE
tabela

### ISSUE THREAD

**Issue by anagolob3141** [anagolob3141/APPR-2017-18#3]
Pozdravljeni,

k svojim podatkom sem želela uvoziti še tabelo, ki opisuje razporeditev valut po državah, da bi lahko narisala zemljevid. Poizkusila sem že nekaj možnosti, vendar vedno dobim le prazno tabelo. Zato vas prosim, če lahko pogledate, kaj delam narobe. Moja koda je:

library(rvest)
library(dplyr)

url <- "https://en.wikipedia.org/wiki/List_of_circulating_currencies"
stran <- html_session(url) %>% read_html()
tabela <- stran %>% html_nodes(xpath="//table[@id='.jquery-tablesorter td']") %>% html_text()

**Comment by jaanos** [comment]
V izvorni kodi spletne strani ni nobenega elementa, ki bi imel podano vrednost atributa `id`, zato je rezultat prazen. Glavna tabela pa ima atribut `class="wikitable sortable"`, tako da lahko to uporabiš:
```R
tabela <- stran %>% html_nodes(xpath="//table[@class='wikitable sortable']") %>%
  .[[1]] %>% html_table(fill = TRUE)
```
Zaradi hrošča v knjižnici `rvest` se bo morda zgodilo, da uvoz ne bo pravilen (vrednosti se pojavljajo v napačnih stolpcih). Če se to zgodi, namesti knjižnico `devtools`, nato pa v konzoli izvedi:
```R
library(devtools)
install_github("jaanos/rvest", ref = "table-span-filling")
```
To bo namestilo razvojno različico knjižnice `rvest`, kjer je ta problem odpravljen.
