### ISSUE TITLE
zaključevanje projekta

### ISSUE THREAD

**Issue by anagolob3141** [anagolob3141/APPR-2017-18#4]
Pozdravljeni,

počasi bi želela zaključiti s projektom. Zanima me,  če se vam zdi, da je analiza dovolj obsežna in ali je kaj še potrebno popraviti?

**Comment by jaanos** [comment]
Trenutno imaš skoraj vso analizo kot aplikacijo Shiny, kar pomeni, da se mora uporabnik sam dokopati do kakršnihkoli ugotovitev. Svetujem, da malo pregledaš podatke, da najdeš kaj zanimivega, pa potem to prikažeš kot statičen graf v poročilu skupaj z interpretacijo.

Imam še sledeče pripombe:
- Ne uporabljaj `\\` v poteh, saj bo to delovalo samo na Windows. Namesto tega uporabi `/` - v `uvoz.r` se tako na tvojo datoteko s podatki sklicuj kot `podatki/tecajiPoMesecih.csv` (na treh mestih).
- Dobim opozorilo, da uporabljaš zastarelo funkcijo `html` (`uvoz.r`, vrstica 65). Namesto nje uporabi `read_html`.
- V poročilo ti izpisuje različna opozorila. Da se to ne bo dogajalo, poskrbi, da bodo glave blokov kode (lahko kar vse) imele parametra `message=FALSE` in `warning=FALSE`.
- Da ti lepo izpiše seznam povezav, postavi pred njega prazno vrstico. Prav tako na koncu postavi prazno vrstico pred tri zvezdice, če želiš izrisati vodoravno črto.
- Zemljevid valut ni najbolj pregleden, saj se imena valut prekrivajo, barve pa se pogosto ne razlikujejo veliko. Svetujem, da oznake odstraniš, različne barve pa daš samo najpogostejšim valutam (ostale naj imajo isto barvo). Pomen barv naj bo razložen v legendi. Potem morda tudi ni smiselno, da imaš ta zemljevid še v aplikaciji Shiny.
- Pri naslednjem zemljevidu najbrž ni bistveno, da so podatki prikazani v taki obliki. Verjetno bo bolje, če podatke za izpostavljene države prikažeš v stolpčnem grafu.
- Pri aplikaciji Shiny imaš trenutno širino nastavljeno na 1500, kar pri majhnih resolucijah pomeni, da bo aplikacija širša kot samo poročilo. Namesto tega jo raje nastavi na širino besedila ter ustrezno nastavi višino, npr. `width="100%", height=800`.

**Comment by anagolob3141** [comment]
Najlepša hvala za odgovor.

Imam še eno vprašanje:
V poročilo bi želela dodati še amplikacijo, ki spreminja graf v odvisnosti od časa z uporabo knjižnjice  gganimate. V projekt.Rmd  na grafu s kodo (oz. v datoteki analiza.r);

`gibanjaTecajev <- ggplot(tecajiSPovprecjem, aes(x= povprecje, y= tecaj, frame = datum, color=kratica)) +
  ggtitle("Gibanje valutnih tečajev v času") +
  xlab("Povprečna višina tečaja") +
  ylab("Visina tecaja glede na čas") +
  theme(legend.position="none") +
  geom_point() +
  geom_text(data=tecajiSPovprecjem,
            aes(x= povprecje, y= tecaj, label=kratica),
            size = 1)
gg_animate(gibanjaTecajev)`

Vendar mi javlja napako: "Error: could not find function "gg_animate"", kljub temu, da naj bi bila knjižnica uspešno naložena. Ali morda veste v čem je težava?

**Comment by jaanos** [comment]
Meni knjižnice `gganimate` ni našlo pri izbiri *Install Packages...*, tako da sem jo moral namestiti iz konzole:
```R
devtools::install_github("dgrtwo/gganimate")
```
Opažam pa, da je funkciji ime `gganimate` (brez podčrtaja), tako da sklepam, da je enako pri tebi.
